---
title: "Using AI in lifescience - A primer"
author: "Nina Norgren"
date: today
---

::: {.callout-warning icon=false}

## About

**Organizers:**                    Sweden AI Factory, NBIS, SciLifeLab Training Hub  
**Date:**                          25 November 2026  
**Location:**                      Online  
**Enrollment opens:**              X September 2026  
**Enrollment closes:**             24 November 2026  
**Course fee:**                    No fee

:::

Course lead: SciLifeLab Training Hub

Course contact: traininghub@scilifelab.se

## Course description

This course introduces you to using AI in lifescience. It covers a number of topics that you should be familiar with if you want to use 
AI consciously and responsibly in your work. We will introduce you to:

- working with agentic AI
- cybersecurity challanges specific to AI-assisted work
- explainable AI illustrated with real life examples
- legal and ethical aspects of AI-assisted work

Throughout the course, we will be focusing on providing examples and illustrating new concepts using cases 
taken from lifescience such as lab practise, clinical medicine, pharmacy etc. 

## Learning Objectives and Learning Outcomes
#### Learning Objectives

- to understand the basics of agentic work
- to be aware of AI-specific cybersecurity challenges and threats and how to prevent them
- to understand what xAI is and why it is particularly important in lifescience
- to be aware of legal implications and challanges related to using AI in your work
- to be aware of ethical aspects of AI-assisted work

#### Learning Outcomes

By the end of this course, learners will be able to:

- use agents to assist you with simple tasks
- identify potential cybersecurity threats and bottlenecks in AI-assisted work
- know how to mitigate the most common cybersecurity risks in their work
- understand what xAI is and be able to explain this concept
- know selected examples of xAI techniques used in lifescience
- evaluate legal and ethical aspects of AI workflows
- plan their AI workflows with ethical and legal perspective in mind


## Target audience and course prerequisites

**Target audience:** doctoral students, postdocs, research support staff  
**Course prerequisites:** none  
**Level:** beginner/intermediate  


## Forms of instruction and examination  

**Forms of instruction:** Lectures, group activities  
**Language:** English    
**Examination:** Active participation in all sessions and group assignments   

